# Generated by Django 4.2.6 on 2023-10-24 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m_venta', '0013_alter_producto_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
