# Generated by Django 4.2.6 on 2023-10-25 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('m_venta', '0015_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='m_venta.categoria'),
            preserve_default=False,
        ),
    ]
