# Generated by Django 4.2.6 on 2023-10-25 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('m_venta', '0017_alter_producto_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
