# Generated by Django 4.2.6 on 2023-10-25 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m_venta', '0020_alter_producto_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='foto',
            field=models.ImageField(null=True, upload_to='img/'),
        ),
    ]
