# Generated by Django 4.2.7 on 2023-11-15 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m_venta', '0021_alter_producto_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='cantidad_fisico',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producto',
            name='cantidad_web',
            field=models.IntegerField(default=0),
        ),
    ]
