# Generated by Django 4.2.7 on 2023-11-16 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m_venta', '0023_carrito_itemcarrito_carrito_productos_carrito_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcarrito',
            name='marca',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemcarrito',
            name='modelo',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
