# Generated by Django 4.2.7 on 2023-11-16 04:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('m_venta', '0024_itemcarrito_marca_itemcarrito_modelo'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcarrito',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
