# Generated by Django 4.2.7 on 2023-11-17 02:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('m_venta', '0025_itemcarrito_usuario'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Carrito',
            new_name='CarritoModel',
        ),
        migrations.RemoveField(
            model_name='itemcarrito',
            name='usuario',
        ),
    ]
