# Generated by Django 4.2.7 on 2023-11-17 02:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('m_venta', '0026_rename_carrito_carritomodel_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CarritoModel',
            new_name='Carrito',
        ),
    ]
