# Generated by Django 4.2.7 on 2023-11-19 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m_venta', '0028_direcciondespacho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direcciondespacho',
            name='direccion',
            field=models.TextField(max_length=100),
        ),
    ]
